// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-Rsz7qPE0Qs-bCezwMIaC06JeaRLI6vY',
    appId: '1:710682455641:web:30675e839afbb3e830cb48',
    messagingSenderId: '710682455641',
    projectId: 'paypay-e1eca',
    authDomain: 'paypay-e1eca.firebaseapp.com',
    storageBucket: 'paypay-e1eca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNBR_t4tzVDuEmXhW0yfBRVqk8Y-DOS5Y',
    appId: '1:710682455641:android:5eb576ed8f30a28c30cb48',
    messagingSenderId: '710682455641',
    projectId: 'paypay-e1eca',
    storageBucket: 'paypay-e1eca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf4wh2wn-bNdCjnzbLCdqDQpvlAVzmgk8',
    appId: '1:710682455641:ios:77d415e46000f3da30cb48',
    messagingSenderId: '710682455641',
    projectId: 'paypay-e1eca',
    storageBucket: 'paypay-e1eca.appspot.com',
    iosBundleId: 'com.domain.salypai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf4wh2wn-bNdCjnzbLCdqDQpvlAVzmgk8',
    appId: '1:710682455641:ios:77d415e46000f3da30cb48',
    messagingSenderId: '710682455641',
    projectId: 'paypay-e1eca',
    storageBucket: 'paypay-e1eca.appspot.com',
    iosBundleId: 'com.domain.salypai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-Rsz7qPE0Qs-bCezwMIaC06JeaRLI6vY',
    appId: '1:710682455641:web:ea3fc11e54bee76c30cb48',
    messagingSenderId: '710682455641',
    projectId: 'paypay-e1eca',
    authDomain: 'paypay-e1eca.firebaseapp.com',
    storageBucket: 'paypay-e1eca.appspot.com',
  );
}
